In [1]:
import numpy as np
from SLE import solve_SLE

**Example:**

$$
2x - y + 3z - 4w = 5 \\
3x + y + z + 2w = 6 \\
x - 2y - z + w = 2 \\
2x + y + 4z + 3w = 7
$$



In [2]:
A = np.array([[2, -1, 3, -4],[3, 1, 1, 2],[1, -2, -1, 1],[2, 1, 4, 3]], dtype = np.float32)
b = np.array([[5.0],[6.0],[2.0],[7.0]])
print(f'A = {A}\n')
print(f'b = {b}')

A = [[ 2. -1.  3. -4.]
 [ 3.  1.  1.  2.]
 [ 1. -2. -1.  1.]
 [ 2.  1.  4.  3.]]

b = [[5.]
 [6.]
 [2.]
 [7.]]


In [3]:
x = solve_SLE(A,b, solver = 'Gaussian')
print(f'x = {x}')
print(A@x)

x = [ 1.67901234 -0.41358035  0.79629632  0.2901235 ]
[5.         6.         2.00000021 7.00000013]


In [4]:
x = solve_SLE(A,b, solver = 'QR')
print(f'x = {x}')
print(A@x)

x = [ 1.67901235 -0.41358025  0.7962963   0.29012346]
[5. 6. 2. 7.]
